### ISSUE TITLE
Not working on Windows in FF and Edge.

### ISSUE THREAD

**Issue by kernelfreak** [JohnMcLear/ep_spellcheck#11]
Hi,

I have installed the plugin and in settings.json have added the following lines 

`"ep_spellcheck":true,`

It works on Linux and Mac, but not on windows. anyway to debug this. Even after enabling from the gear icon it doesn't work. Thank you.

**Comment by jinbullsushil** [comment]
> Hi,
> 
> I have installed the plugin and in settings.json have added the following lines
> 
> `"ep_spellcheck":true,`
> 
> It works on Linux and Mac, but not on windows. anyway to debug this. Even after enabling from the gear icon it doesn't work. Thank you.

Hi,

I had faced the same problem,

**Comment by akshaysgithub** [comment]
> > Hi,
> > I have installed the plugin and in settings.json have added the following lines
> > `"ep_spellcheck":true,`
> > It works on Linux and Mac, but not on windows. anyway to debug this. Even after enabling from the gear icon it doesn't work. Thank you.
> 
> Hi,
> 
> I had faced the same problem,
> Modify your js file with below script.
> 
> var spellcheck = {
> enable: function() {
> $('.check_spell_check').removeClass('unchecked_spell_check').addClass('checked_spell_check');
> $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").attr("spellcheck","true");
> 
> ```
>   $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").find('div').each(function() {
> 		$(this).attr("spellcheck","true");
>   });
>   
> },
> disable: function() {
>   $('.check_spell_check').removeClass('checked_spell_check').addClass('unchecked_spell_check');	
>   $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").attr("spellcheck","false");
>   $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").find('div').each(function() {
> 		$(this).attr("spellcheck","false");
>   });
> }
> ```
> 
> }

Which JS file?

**Comment by jinbullsushil** [comment]
> > > Hi,
> > > I have installed the plugin and in settings.json have added the following lines
> > > `"ep_spellcheck":true,`
> > > It works on Linux and Mac, but not on windows. anyway to debug this. Even after enabling from the gear icon it doesn't work. Thank you.
> > 
> > 
> > Hi,
> > I had faced the same problem,
> > Modify your js file with below script.
> > var spellcheck = {
> > enable: function() {
> > $('.check_spell_check').removeClass('unchecked_spell_check').addClass('checked_spell_check');
> > $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").attr("spellcheck","true");
> > ```
> >   $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").find('div').each(function() {
> > 		$(this).attr("spellcheck","true");
> >   });
> >   
> > },
> > disable: function() {
> >   $('.check_spell_check').removeClass('checked_spell_check').addClass('unchecked_spell_check');	
> >   $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").attr("spellcheck","false");
> >   $('iframe[name="ace_outer"]').contents().find('iframe').contents().find("#innerdocbody").find('div').each(function() {
> > 		$(this).attr("spellcheck","false");
> >   });
> > }
> > ```
> > 
> > 
> > }
> 
> Which JS file?

Hi ,
**ep_spellcheck\static\js\spellcheck.js**

**Comment by CarliJoy** [comment]
Maybe you coud open a Merge Request with this change?

**Comment by JohnMcLear** [comment]
This fix doesn't work.  Each time the DOM is redraw the Divs lose their attribute...

**Comment by JohnMcLear** [comment]
So it turns out this is working "as expected".  Browsers are broken.

It has nothing to do with the logic/code here, it's how browsers are implementing the spellcheck attribute on divs/child elements in browsers.  I get a realtively broken UX in FF/Chrome/Edge.

I wlil submit a proper fix but it's not good, the problem is that unless the content comes into focus browsers don't waste their time spellchecking and flagging.  This is fair behavior.

**Comment by JohnMcLear** [comment]
I put a temporary fix in that will mean spellcheck works but the UX is limited by browsers and because Etherpad re-renders the DOM on edits and when it does the re-render it can lose the attribute and browers don't(always) let the attribute proprogate to children.

Give it a try and re-open if this doesn't work.  npm package published.
