### ISSUE TITLE
Please publish version 0.0.4 on npmjs.com

### ISSUE THREAD

**Issue by ldidry** [JohnMcLear/ep_spellcheck#13]
Could you publish the version 0.0.4 on npmjs.com, please? The localization is one thing that has been added since 0.0.3 and we would like to have it 

Thank you :slightly_smiling_face:

**Comment by JohnMcLear** [comment]
done


Secret, Proprietary & Confidential

This electronic message transmission contains information which is proprietary and confidential. The information is intended solely for the intended recipient, and use by any other party is not authorized.
________________________________

**Comment by ldidry** [comment]
Thank you :blush:
